#!/usr/bin/env python3
"""
build_zip_crosswalk.py — California ZIP -> county-FIPS crosswalk for ModularZ.

Lets the tool turn a deal address/ZIP into the county whose CTCAC AMI rents
apply (pairs with hud_rents.js). Source of truth: U.S. Census Bureau 2020 ZCTA
-> County relationship file (public, no auth). A CA-only subset is stashed in
source/ca_zcta_county_2020.psv for reproducibility.

ZCTAs that span multiple counties are resolved to the county with the largest
land-area overlap (AREALAND_PART), i.e. the dominant county for that ZIP.

Output:
  web/static/ca_zip_county.js    -> window.CA_ZIP_COUNTY = {"90061":"06037", ...}
  web/static/ca_zip_county.json

Refresh when the Census releases a new relationship file: replace the .psv in
source/ (or re-filter the national file to CA county GEOIDs ^06\\d{3}$) and re-run.

Note: ZCTAs approximate USPS ZIPs; a handful of PO-box-only ZIPs have no ZCTA.
Fall back to the built-in market map / AI county when a ZIP isn't found.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "source", "ca_zcta_county_2020.psv")
OUT_DIR = os.path.normpath(os.path.join(HERE, "..", "static"))
OUT_JS = os.path.join(OUT_DIR, "ca_zip_county.js")
OUT_JSON = os.path.join(OUT_DIR, "ca_zip_county.json")

SOURCE = "U.S. Census Bureau 2020 ZCTA-to-County Relationship File (CA subset)"
SOURCE_URL = "https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/tab20_zcta520_county20_natl.txt"

SPOTCHECKS = {"90061": "06037", "91403": "06037", "92101": "06073",
              "94110": "06075", "95814": "06067"}  # LA, Sherman Oaks, SD, SF, Sacramento


def main():
    if not os.path.exists(SRC):
        sys.exit(f"Source not found: {SRC}")
    best = {}  # zip -> (county_fips, arealand_part)
    with open(SRC, encoding="utf-8-sig") as f:
        header = f.readline()
        for line in f:
            p = line.rstrip("\n").split("|")
            if len(p) < 17:
                continue
            zcta, county, area = p[1].strip(), p[9].strip(), p[16].strip()
            if not zcta or not county.startswith("06"):
                continue
            try:
                area_v = int(area) if area else 0
            except ValueError:
                area_v = 0
            if zcta not in best or area_v > best[zcta][1]:
                best[zcta] = (county, area_v)

    crosswalk = {z: fips for z, (fips, _) in sorted(best.items())}

    for z, exp in SPOTCHECKS.items():
        got = crosswalk.get(z)
        if got != exp:
            sys.exit(f"VALIDATION FAILED: {z} expected {exp}, got {got}")

    counties = sorted(set(crosswalk.values()))
    payload = {
        "_meta": {"source": SOURCE, "sourceUrl": SOURCE_URL,
                  "note": "ZIP->county FIPS, dominant county by land-area overlap. "
                          "Pairs with hud_rents. Fall back to market map / AI county if a ZIP is absent.",
                  "zips": len(crosswalk), "countiesCovered": len(counties)},
        "zipToCounty": crosswalk,
    }
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_JSON, "w") as f:
        json.dump(payload, f, indent=2)
    with open(OUT_JS, "w") as f:
        f.write("// AUTO-GENERATED by web/hud_rents/build_zip_crosswalk.py — do not edit by hand.\n")
        f.write(f"// {SOURCE}\n")
        f.write("window.CA_ZIP_COUNTY = ")
        json.dump(crosswalk, f)
        f.write(";\n")
    print(f"OK — {len(crosswalk)} CA ZIPs -> {len(counties)} counties.")
    print(f"  {OUT_JS}\n  {OUT_JSON}")
    print("Spot-checks passed: 90061/91403->LA, 92101->SD, 94110->SF, 95814->Sacramento.")


if __name__ == "__main__":
    main()
